"""
scripts/evaluate_detector.py
============================
Evaluate YOLOv8 player detector.

PRD Reference: Task 1.3, GOAL-15
Reports mAP@0.5 per class on the test split.
"""

import argparse
import logging
from pathlib import Path

from ultralytics import YOLO

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

def evaluate(model_path: str, data_yaml: str) -> None:
    """Run evaluation and report mAP@0.5 per class."""
    if not Path(model_path).exists():
        logging.error(f"Model weights not found at {model_path}. Did you run training?")
        return

    logging.info(f"Loading model {model_path}...")
    model = YOLO(model_path)

    logging.info(f"Evaluating model on test split using {data_yaml}...")
    # By default model.val() evaluates on the validation split defined in the yaml.
    # To evaluate on test split, we pass split="test"
    metrics = model.val(data=data_yaml, split="test", conf=0.40, iou=0.50)

    # YOLO val returns a metrics object. We can print the relevant stats.
    # The map50 is the mAP@0.5 we care about for GOAL-15.
    print("\n" + "="*50)
    print("EVALUATION RESULTS")
    print("="*50)
    
    class_names = metrics.names
    # map50 per class (array of length = num classes)
    maps50 = metrics.box.maps  # map50-95 per class? Actually, metrics.box.map50 is a float, 
                               # but metrics.class_result() gives per-class.
                               # Ultralytics API: metrics.box.maps is map50-95 per class.
                               
    # Ultralytics metrics dictionary structure is slightly complex. 
    # Usually it prints a nice table to the console automatically.
    # But we can extract map50 overall:
    print(f"Overall mAP@0.5 : {metrics.box.map50:.4f}")
    print(f"Overall mAP@.5-.95: {metrics.box.map:.4f}")
    print("-" * 50)
    
    # Let's print the automatic table generated by ultralytics which is in console anyway.
    logging.info("Check the Ultralytics output above for detailed per-class mAP@0.5.")
    print("="*50 + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=str, default="models/player_detector/weights/best.pt", 
                        help="Path to trained YOLOv8 model weights")
    parser.add_argument("--data", type=str, default="configs/dataset.yaml",
                        help="Path to dataset YAML file")
    
    args = parser.parse_args()
    evaluate(args.model, args.data)
